
services:
  filetransferapp:
    image: filetransferapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./ssh_keys/ssh_host_ed25519_key:/root/.ssh/ssh_host_ed25519_key
      - ./ssh_keys/ssh_host_rsa_key:/root/.ssh/ssh_host_rsa_key
    depends_on:
      - sftp-server
      - minio

  sftp-server:
    image: rastasheep/ubuntu-sshd
    container_name: sftp-server
    ports:
      - "2222:22"
    volumes:
      - ./data:/data
    environment:
      - ROOT_PASSWORD=password
    command: /bin/sh -c "echo 'root:password' | chpasswd && mkdir -p /data && chmod 777 /data && exec /usr/sbin/sshd -D"
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9002:9001"
    volumes:
      - ./minio_storage:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=passminio
      - MINIO_DEFAULT_BUCKETS=minio
    command: server --console-address ":9001" /data

networks:
  default:
    driver: bridge